name: news_app
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.4.0-82.0.dev <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6


  #Config
  flutter_gen_runner: ^5.5.0+1
  json_annotation: ^4.9.0
 
  #Fonts
  google_fonts: ^6.2.1
  
  # Network
  dio: ^5.4.3+1

  #Slider
  carousel_slider_plus: ^6.0.0

  #State Management
  flutter_riverpod: ^2.5.1

  #Cache
  cached_network_image: ^3.3.1
  
  #Firebase
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  #Runner
  build_runner: ^2.4.11

  #Json
  json_serializable: ^6.8.0

  #Envied
  flutter_dotenv: ^5.1.0

  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/color/
    - assets/images/
    - assets/icons/
    - .env
   
flutter_gen:
  output: lib/product/generation/
  assets:
    enabled: true

  colors:
    inputs: 
      - assets/color/color.xml