// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwZ1g9tRqhjCdXr4OWGCLEbwTGYmd7oJE',
    appId: '1:1029695647778:web:388a9f6ee37cd5bda01a7b',
    messagingSenderId: '1029695647778',
    projectId: 'news-app-14b7c',
    authDomain: 'news-app-14b7c.firebaseapp.com',
    storageBucket: 'news-app-14b7c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBksTZU__NCgAU9SDkrCF1mEgfpyeP-qu4',
    appId: '1:1029695647778:android:cf047e1516b1236ca01a7b',
    messagingSenderId: '1029695647778',
    projectId: 'news-app-14b7c',
    storageBucket: 'news-app-14b7c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK07acm2EoMyYHkRixBr7HP5ebiRI_eBc',
    appId: '1:1029695647778:ios:7f720fad5e9f0030a01a7b',
    messagingSenderId: '1029695647778',
    projectId: 'news-app-14b7c',
    storageBucket: 'news-app-14b7c.appspot.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAK07acm2EoMyYHkRixBr7HP5ebiRI_eBc',
    appId: '1:1029695647778:ios:7f720fad5e9f0030a01a7b',
    messagingSenderId: '1029695647778',
    projectId: 'news-app-14b7c',
    storageBucket: 'news-app-14b7c.appspot.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwZ1g9tRqhjCdXr4OWGCLEbwTGYmd7oJE',
    appId: '1:1029695647778:web:ef17076d575dda91a01a7b',
    messagingSenderId: '1029695647778',
    projectId: 'news-app-14b7c',
    authDomain: 'news-app-14b7c.firebaseapp.com',
    storageBucket: 'news-app-14b7c.appspot.com',
  );
}
